<?php
require_once 'app/Mage.php';

//Mage::getSingleton("customer/session", array("name" => "frontend"));
$open=Mage::app()->getRequest()->getParam('customer_show');
$expressmail=Mage::app()->getRequest()->getParam('show_express_email');
$express_email=Mage::app()->getRequest()->getParam('email');

if (isset($open) &&$open>=0) {
    Mage::run('','store');
    Mage::getSingleton("customer/session", array("name" => "frontend"));
    Mage::getModel('customer/session')->setNeedHelp($open);
}

if (isset($expressmail) && $expressmail>=0) {
	Mage::app ( 'default' );
	
	$time =60*60*24*7*4*$expressmail; // 4 Weeks
	Mage::getModel('core/cookie')->set('express_mail5', $expressmail, $time);
	 
	if (isset($express_email) && strlen($express_email)>0) {				
		Mage::getModel('core/cookie')->set('express_email', $express_email, $time);
		Mage::run('','store');
		$session = Mage::getSingleton('checkout/session');
		$session_quote_id=$session->getQuote()->getId();
		if (!empty($session_quote_id)) {
			$session->getQuote()->setCustomerEmail($express_email)->save();			 
		}
		// create customer if we need that
// 		/* $customer_email = 'aliaksandrl@expressdecor.com';  // email adress that will pass by the questionaire
// 		$customer_fname = 'Customer';      // we can set a tempory firstname here
// 		$customer_lname = '';       // we can set a tempory lastname here
// 		$passwordLength = 10;                    // the lenght of autogenerated password
		
// 		$customer = Mage::getModel('customer/customer');
// 		$customer->setWebsiteId(Mage::app()->getWebsite()->getId());
// 		$customer->loadByEmail($customer_email);
		
// 		/*
// 		 * Check if the email exist on the system.
// 		* If YES,  it will not create a user account.
// 		*/
		
// 		if(!$customer->getId()) {		
// 			//setting data such as email, firstname, lastname, and password		
// 			$customer->setEmail($customer_email);
// 			$customer->setFirstname($customer_fname);
// 			$customer->setLastname($customer_lname);
// // 			$customer->setPassword($customer->generatePassword($passwordLength));		
// 		}
// 		try{
// 			//the save the data and send the new account email.
// 			$customer->setPassword($customer->generatePassword($passwordLength));
// 			$customer->save();
// 			$customer->setConfirmation(null);
// 			$customer->save();
// 			$customer->sendNewAccountEmail();
// 		}
// 		catch(Exception $ex){
		
// 		 */}
		//end of create customer 
		
	}
	 
}   

 
?>
 