<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('catalog')->__('Manage Tasks') ?></h3></td>
        <td class="a-right">
            <?php echo $this->getButtonsHtml() ?>
        </td>
    </tr>
</table>
</div>
<div id="add-new-list" style="display:none; margin-bottom: 25px;">
    <h2><strong><?php echo $this->__('Add a list'); ?></strong></h2>
    <label for="list-name"><?php echo Mage::helper('nicommerce_taskmanager')->__('List Name:'); ?></label><br />
    <input type="text" name="list-name" id="list-name" value="" class="input-text" /><br />
    <label for="list-description"><?php echo Mage::helper('nicommerce_taskmanager')->__('List Description:'); ?></label><br />
    <textarea rows="5" cols="100" name="list-description" id="list-description" value=""></textarea><br />
    <button class="scalable save" type="button" id="save-list"><span><?php echo Mage::helper('nicommerce_taskmanager')->__('Save'); ?></span></button>
</div>
<div class="clear"></div>
<div style="padding:0 0 10px; text-align: right;">
    <?php echo Mage::helper('nicommerce_taskmanager')->__('Filter tasks by priority:'); ?>
    <select id="prioritySelectah">
        <option value="any"><?php echo Mage::helper('nicommerce_taskmanager')->__('any');?></option>
        <?php
        for ( $i=1; $i<=5; $i++ )
        {
            echo '<option value="'.$i.'"';
            if ( $i == $this->getPriorityFilter() ) {
                echo ' selected ';
            }
            echo '>'.Mage::helper('nicommerce_taskmanager')->__($i).'</option>';
        } ?>
    </select>
    <script type="text/javascript">
        $('prioritySelectah').observe('change', function(){
            //alert($('prioritySelectah').value);
            var prioValue = $('prioritySelectah').value;
            window.location.href = '<?php echo Mage::getSingleton('adminhtml/url')->getUrl('*/*/index/'); ?>priority/'+prioValue;
        });
    </script>
</div>
<div id="ajax-content">
    <div id="grid-content">
        <?php echo $this->getGridHtml() ?>
    </div>
    <div>
        <?php echo $this->getJsHtml() ?>
    </div>
</div>
