<?php $skin_path = $this->getPathSkin(); ?>
<script type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $skin_path; ?>/jquery-ui-1.8.custom/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?php echo $skin_path; ?>/plugins/jquery.form.js"></script>
<script type="text/javascript">

jQueryCommercebug.noConflict();

</script>
<script type="text/javascript" src="<?php echo $skin_path; ?>/jquery-ui-1.8.custom/js/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $skin_path; ?>/jquery-ui-1.8.custom/js/jquery-ui-1.8.custom.min.js"></script>
<script type="text/javascript" src="<?php echo $skin_path; ?>/jquery-ui-1.8.custom/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="<?php echo $skin_path; ?>/commercebug.js"></script>