<div id="ascommercebug_controllers_results">
	<table id="ascommercebug_controllers_results_table" class="tablesorter">
		<thead>
			<tr>
				<th>
					<?php echo $this->__('Label'); ?>
				</th>
				<th>
					<?php echo $this->__('Value'); ?>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					<?php echo $this->__('Controller Class Name'); ?>
				</td>
				<td>
					<span id="ascommercebug_controllers_classname" class="classname"></span> 
					<br />
					<span id="ascommercebug_controllers_filename" class="pathinfo"></span> 
				</td>
			</tr>
			<tr>
				<td>
					<?php echo $this->__('Full Action Name'); ?>
				</td>
				<td>
					<span id="ascommercebug_controllers_full_actionname"></span>
				</td>
			</tr>
			<tr>
				<td>
					<?php echo $this->__('Module Name'); ?>
				</td>
				<td>
					<span id="ascommercebug_controllers_modulename"></span>
				</td>
			</tr>
			<tr>
				<td>
					<?php echo $this->__('Controller Name'); ?>
				</td>
				<td>
					<span id="ascommercebug_controllers_controllername"></span>
				</td>
			</tr>
			<tr>
				<td>
					<?php echo $this->__('Action Name'); ?>
				</td>
				<td>
					<span id="ascommercebug_controllers_actionname"></span>
				</td>
			</tr>
			<tr>
				<td>
					<?php echo $this->__('Path Info'); ?>
				</td>
				<td>
					<span id="ascommercebug_controllers_pathinfo"></span>
				</td>
			</tr>
		</tbody>
	</table>
</div>
