<?php
//coupon & showwindow
$show_window=Mage::app()->getRequest()->getParam('show_window');
$coupon=Mage::app()->getRequest()->getParam('coupon');
 
if (Mage::getSingleton ( 'cms/page' )->getIdentifier () != 'home'  && $coupon && $show_window) {

?>
 <script type="text/javascript">
 jQuery(document).ready(function() { 
	 jQ('.page > div').each(function() { 
		 if ( jQ(this).attr("id") !='express-coupon')
		 	jQ(this).css('opacity','0.5');
	 });

	 jQ.get('/page/popupwindow/getparameters',  {coupon: '<?php echo $coupon;?>'},function(data){    
	   if (data.length>0){           	 
	  	 params=jQ.parseJSON(data);	  	 
	  	 jQ('.coupon-descr').html(params.label);
		 jQ('.coupon-code').html(params.code);
		}  
		         
	});     
	 
   	}); 

function close_coupon_window() {	
	 jQ('.page > div').each(function() { 
		 if ( jQ(this).attr("id") !='express-coupon')
		 	jQ(this).css('opacity','1');
	 });
	 
	 jQ('.express-coupon').hide();  
}
 </script>	
 
<div id="express-coupon" class="express-coupon <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>">

<a href="javascript:void(0)" onclick="close_coupon_window()"><div class="close-coupons-window"></div></a>
<div class="coupon-descr"><?php echo $label;?></div>
<a href="javascript:void(0)" onclick="close_coupon_window()"><div class="coupon-code"><?php echo $coupon_code;?></div></a>
<div class="coupon-promo-text"><?php echo $this->__('use this coupon code at checkout');?></div>
</div>
<?php 
}