 <script type="text/javascript">

/*<![CDATA[*/
window.fbAsyncInit = function() {
	FB.init({appId: '<?php echo Mage::helper('facebook')->getAppId()?>',             
	    status     : true, 
            cookie     : true,
            xfbml      : true,
            oauth      : true});
  
};
(function(d){
           var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
           js = d.createElement('script'); js.id = id; js.async = true;
           js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getLocaleCode()?>/all.js";
           d.getElementsByTagName('head')[0].appendChild(js);
         }(document));


function sign_in(){ 
	jQuery(".emails-overlay").show();
	jQuery(".express-emails").each(function() {			 
		jQuery(this).fadeOut();
	});
	 
	jQuery(".validation-advice").each(function() {			 
		jQuery(this).remove();
	});
	
 
	jQuery(".express-emails.welcome-back").fadeIn();	
  }
  
/*]]>*/


/*<![CDATA[*/
function fblogin(){
FB.login(function(response) {
   if (response.status == 'connected') {  
        login();
    } else {       
    	alert("It was error, processing your request. Please, try again.");
    }
}, {scope:'email,publish_stream'});
return false;
}

function login(){	
	jQ.get('/facebook/facebook/fblogin',  {facebook_login: 1},function(data){    
		if (data!='"success"'){           	 
			alert("It was error, processing your request. Please, try again.");
    	} else {
        	update_account_links();
        	popup_close();
        	location.reload(); 
        }                
	}); 
}
	
function popup_close(){   
	jQ.get('/facebook/facebook/closewindow',  {close:1},function(data){ }); 	
	jQ(".express-emails").each(function() {
		jQ(this).fadeOut();
	});               
jQ('.emails-overlay').fadeOut();                        
}

function update_account_links(){
 // Update Account links      
	jQ.get('/facebook/facebook/updatelinks',  {},function(data){
		jQ(".header-login .links").remove();
		jQ(".header-login").append(data);
	} , 'json');     
}

function join_us(){ 
	  jQuery(".emails-overlay").show();
	  jQuery("#form-validate-join").show();
	  jQuery(".additional_info").hide();
	jQuery(".express-emails").each(function() {
		jQuery(this).fadeOut();
	});
	jQuery(".validation-advice").each(function() {			 
		jQuery(this).remove();
	});
	jQuery(".express-emails .registered").each(function() {				 	 
		jQuery(this).remove();
	});
	jQuery(".express-emails.join-us .singup-text").show();
	jQuery(".express-emails.join-us").fadeIn();	
}

function post_request(obj) {	  
	  var f =jQuery(obj).closest("form").attr("id");		  
	  var validation=0;
	  var type=0;
		if (f=='form-validate-to') {
			//jQuery("#advice-validate-email-email_address").remove();
			validation=dataFormto.validator.validate();
			type=1; 
		}
		if (f=='form-validate-back') {
			//jQuery("#advice-validate-email-newsletter").remove();
			validation=dataFormback.validator.validate(); 
			type=2;
		}
		if (f=='form-validate-join') {
			//jQuery("#advice-validate-email-newsletter").remove();
			validation=dataFormjoin.validator.validate(); 
			type=3;
		}

		jQuery("#advice-validate-email-email_address").remove(); 
		
	    if (validation){
	    	var email_str=jQ('#'+f+" #email_address").val();
	        jQuery('#'+f+" #email_address").css("background-color","#bfffbf");
	        var password='';
	        if (type==2 || type==3){		       	 	
			 	jQuery('#'+f+" #password").css("background-color","#bfffbf");
			 	password=jQ('#'+f+" .real-password").val();
	        }
	       	           	        	 
	     	jQuery(obj).hide(); 
	     	jQuery(obj).parent().children(".popup-loader").show();
	     	 
	        jQ.get('/facebook/facebook/login',  { email:email_str, password:password, type:type},function(data){              
	        	if ( data=='success'){
	            	update_account_links();
	            	popup_close();
	            	jQuery(obj).parent().children(".popup-loader").hide();
	            	jQuery(obj).show();	            	
	            	location.reload(); 
	            	//jQuery(".express-emails.join-us .singup-info").append("<div class=\"registered\"><?php //echo $this->__('Thank you for registration. Your account information will be sent to your email address.');?></div>");
	            }else {		        	 
		            jQuery("#advice-validate-email-email_address").remove();
	    			var error_text='<div style="" id="advice-validate-email-email_address" class="validation-advice">'+data+'</div>';  	    	 	
	    			jQ('#'+f+' .singup-left .email-field').append(error_text);  
	    			jQuery(obj).parent().children(".popup-loader").hide();  
	    			jQuery(obj).show();					 
	        	}                
	        },'json'); 
	                   
	      }
}

function forgot_pass(obj){	
	jQuery('#advice-validate-email-email_address').remove();	 
	var email=jQ('#'+jQuery(obj).closest("form").attr("id")+' #email_address');
	var val=false;
	val=Validation.validate(email.get(0));
 
	if (val){		  		
		jQuery(obj).hide();
		jQuery(obj).parent().children(".popup-loader").show();
		jQ.get('/facebook/facebook/forgotpass',  { email:email.val(),},function(data){
			if (data) {			     		 
				var validate_text='<div id="advice-validate-email-email_address" class="validation-advice">'+data+'</div>';  			    
				jQ('#'+jQuery(obj).closest("form").attr("id")+' .email-field').append(validate_text);
				jQuery(obj).parent().children(".popup-loader").hide();	
				jQuery(obj).show();		
			}  
		},'json');
	} 
}

jQuery(document).ready(function() { 
	jQuery(".express-emails :input").each(function() {
		jQuery(this).focusout(function() {
			var f =jQuery(this).closest("form").attr("id");
			validation=0;			
			jQuery('#advice-validate-email-email_address').remove();			
			if (f=='form-validate-to') {
				validation=dataFormto.validator.validate(); 				
			}
			if (f=='form-validate-back') {
				validation=dataFormback.validator.validate(); 
			}
			if (f=='form-validate-join') {
				validation=dataFormjoin.validator.validate();
			}
			 
		 });		 		 		 
		});	 
	
  	}); 
/*]]>*/ 
</script>
<!-- facebook  -->
<div class="emails-overlay" style="display: none;"></div>
<!-- homepage -->
<?php
$url = Mage::getBaseUrl ( Mage_Core_Model_Store::URL_TYPE_WEB );
$popup_window_enabled=Mage::getStoreConfig('facebook/settings/enabled',Mage::app()->getStore());
 
if (Mage::getSingleton ( 'cms/page' )->getIdentifier () == 'home' && Mage::app ()->getFrontController ()->getRequest ()->getRouteName () == 'cms' && $popup_window_enabled) {
	?>


<div class="express-emails <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?> welcome-to" style="display: none;">
	<div class="express-mails-title <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div>
	<a href="javascript:void(0);" onclick="popup_close();"><div class="express-mails-close <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div></a>
	<div class="singup-info">
		<div class="singup-text"><?php echo $this->__("Do you have your ExpressAccount yet?");?></div>
		 

	</div>
	<div class="sign-up">
		<form id="form-validate-to" method="post" action="">
			<div class="singup-left">
				<div class="email-field reg-field">
					<div class="email-label reg-label"><?php echo $this->__("Email Address:");?></div>
					<input type="text" class="input-text validate-email required-entry dataFormto" title="Email Address" value="" id="email_address" name="email"  />
				</div>				 
			</div>
			<div class="singup-right">
				<div class="singup-button">
					<button   title="Join" class="button"  onclick="post_request(this);"   type="button"><div><span><?php echo $this->__('Join Us');?></span></div></button>
					<div class="popup-loader" style="display:none;"></div> 
				</div>		 
			</div>
		</form>
	</div>
	<div class="or-fb"><?php echo $this->__('or'); ?></div>
	<div class="fb-container">
		<div class="fb-login">
			<a href="#" onclick="return fblogin();" class="fb_button_ps"><div
					class="fb-logo"></div></a>
		</div>
		<div style="display:none;" class="fb-text"><?php echo $this->__('ExpressDecor.com will never post without your permission.');?></div>
	</div>
	<div class="footer-cont">
		<div class="member-block">
			<span class="question-part"><?php echo $this->__('Already member?')?></span>
			<span onclick="sign_in();" class="action-part"><?php echo $this->__('Sign in!')?></span>
		</div>
		<div class="footer-text">
		<?php echo $this->__("It's fast and easy. Get access to ExpressAccount Only discounts!");?>
	</div>

	</div>
</div>
<script type="text/javascript">
//<![CDATA[
  var dataFormto = new VarienForm('form-validate-to', false);   	
    jQ.get('/facebook/facebook/islogged',  {},function(data){      
        if (data==0) {
       	jQ('.emails-overlay').show();
        jQ(".express-emails.welcome-to").show();       
        }
    }); 
//]]>  
</script>
<?php } ?>
<!--  welcome back -->
<div class="express-emails welcome-back <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>" style="display: none;">
	<div class="express-mails-title <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div>
	<a href="javascript:void(0);" onclick="popup_close();"><div class="express-mails-close <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div></a>
	<div class="singup-info">
		<div class="singup-text"><?php echo $this->__("Welcome back! Please login");?></div>
	</div>
	<div class="sign-up">
		<form id="form-validate-back" method="post" action="">
			<div class="singup-left">
				<div class="email-field reg-field">
					<div class="email-label reg-label"><?php echo $this->__("Email Address:");?></div>
					<input type="text" class="input-text validate-email required-entry dataFormback"
						title="Email Address" value="" id="email_address" name="email" value="" />
				</div>
				<div class="pass-field reg-field">
					<div class="pass-f1">
						<div class="pass-label reg-label"><?php echo $this->__("Password:");?></div>
						<input type="password"
							class="input-text required-entry validate-password real-password"
							title="Password" id="password" name="password" value="" />
					</div>
				</div>
			</div>
			<div  class="singup-right">
				<div class="singup-button">
					<button   title="Sign In" class="button"  onclick="post_request(this);" type="button"><div><span><?php echo $this->__('Sign In');?></span></div></button>
					<div class="popup-loader" style="display:none;"></div>
				</div>
				<div class="forgot-button">
					<button   title="Forgot Password" class="button"  onclick="forgot_pass(this);" type="button"><div><span><?php echo $this->__('Forgot Password?');?></span></div></button>
					<div class="popup-loader" style="display:none;"></div>
				</div>							 
			</div>
		</form>
	</div> 
	<div class="footer-cont">
		<div class="member-block">
			<span class="question-part"><?php echo $this->__('Not a  member yet?')?></span>
			<span onclick="join_us();" class="action-part"><?php echo $this->__('Join Now!')?></span>
		</div>
		<div class="footer-text">
		<?php echo $this->__("Make sure that you can see all of our great savings, sales and discounts!");?>
	</div>

	</div>
</div>
<script type="text/javascript">
//<![CDATA[
  var dataFormback = new VarienForm('form-validate-back', false);
//]]>  	 
</script>
<!-- join us  -->
<div class="express-emails join-us <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>" style="display: none;">
	<div class="express-mails-title <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div>
	<a href="javascript:void(0);" onclick="popup_close();"><div class="express-mails-close <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div></a>
	<div class="singup-info">
		<div class="singup-text"><?php echo $this->__("Thanks for visiting! Thart savings instantly");?></div>
	</div>
	<div class="sign-up">
		<form id="form-validate-join" method="post" action="">
			<div class="singup-left">
				<div class="email-field reg-field">
					<div class="email-label reg-label"><?php echo $this->__("Email Address:");?></div>
					<input type="text" class="input-text validate-email required-entry dataFormjoin"
						title="Email Address" value="" id="email_address" name="email" value="" />
				</div>
				<div class="pass-field reg-field">
					<div class="pass-f1">
						<div class="pass-label reg-label"><?php echo $this->__("Password:");?></div>
						<input type="password"
							class="input-text required-entry validate-password real-password"
							title="Password" id="password" name="password" value="" />
					</div>
				</div>
			</div>
			<div class="singup-right">	
				<div class="singup-button">
					<button   title="Join Us" class="button" onclick="post_request(this);" type="button"><div><span><?php echo $this->__('Join Us');?></span></div></button>
					<div class="popup-loader" style="display:none;"></div>
				</div>
			</div>

		</form>
	</div>
	<div class="footer-cont">
		<div class="member-block">
			<span class="question-part"><?php echo $this->__('Already member?')?></span>
			<span onclick="sign_in();" class="action-part"><?php echo $this->__('Sign in!'); ?></span>			
		</div>
		<div class="footer-text">
		<?php echo $this->__("Make sure that you can see all of our great savings, sales and discounts!");?>
	</div>

	</div>
</div>
<script type="text/javascript">
//<![CDATA[
  var dataFormjoin = new VarienForm('form-validate-join', false);
//]]>  	 
</script>
