 <script type="text/javascript">

/*<![CDATA[*/
window.fbAsyncInit = function() {
	FB.init({appId: '<?php echo Mage::helper('facebook')->getAppId()?>',             
	    status     : true, 
            cookie     : true,
            xfbml      : true,
            oauth      : true});
  
};
(function(d){
           var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
           js = d.createElement('script'); js.id = id; js.async = true;
           js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getLocaleCode()?>/all.js";
           d.getElementsByTagName('head')[0].appendChild(js);
         }(document));


function sign_in(){ 
	jQuery(".emails-overlay").show();
	jQuery(".express-emails").each(function() {			 
		jQuery(this).fadeOut();
	});
	 
	jQuery(".validation-advice").each(function() {			 
		jQuery(this).remove();
	});
	
	jQuery('.express-emails.welcome-back .agreement-txt').show();
	jQ('.express-emails.welcome-back .agreement-txt').html("<?php echo $this->__('<a onclick=\"forgot_pass(\'\');\" href=\"#\">Forgot your password?</a>');?>");
	jQuery(".express-emails.welcome-back").fadeIn();	
  }
  
/*]]>*/


//<![CDATA[
function fblogin(){
FB.login(function(response) {

   if (response.status == 'connected') {  
        login();
    } else {       
        // user is not logged in
        //window.location.reload();
    }
}, {scope:'email,publish_stream'});
return false;
}

function login(){
	 
	 jQ.get('/facebook/facebook/fblogin',  {facebook_login: 1},function(data){    
	if (data!='"success"'){           	 
					alert("It was error, processing your request. Please, try again.");
        } else {
        	update_account_links();
        	popup_close();
        	window.location="/customer/account/login/"; 
        }                
}); 
	}
function popup_close(){   
	 jQ.get('/facebook/facebook/closewindow',  {},function(data){ }); 
	
	jQ(".express-emails").each(function() {
		jQ(this).fadeOut();
	});               
jQ('.emails-overlay').fadeOut();                        
}

function update_account_links(){
 // Update Account links      
jQ.get('/facebook/facebook/updatelinks',  {},function(data){
	jQ(".header-login .links").remove();
	jQ(".header-login").append(data);
} , 'json');     
}


function join_us(){ 
	  jQuery(".emails-overlay").show();
	  jQuery("#form-validate-join").show();
	  jQuery(".additional_info").hide();
	jQuery(".express-emails").each(function() {
		jQuery(this).fadeOut();
	});
	jQuery(".validation-advice").each(function() {			 
		jQuery(this).remove();
	});
	jQuery(".express-emails .registered").each(function() {				 	 
		jQuery(this).remove();
	});
	jQuery(".express-emails.join-us .singup-text").show();
	jQuery(".express-emails.join-us").fadeIn();	
}


function second_step(type){
	  jQuery(".express-emails").each(function() {
			jQuery(this).fadeOut();
	   });
	  var email_str=jQ(type+" #email_address").val(); 
	  jQ(".express-emails.join-us #email_address").val(email_str); 
	  jQuery("#form-validate-join").hide(); 
	  jQuery(".express-emails.join-us").fadeIn();	
	  jQuery(".express-emails.join-us .singup-text").hide();
	  jQuery(".additional_info").fadeIn();		   		  
	  jQuery(".express-emails.join-us .singup-info").append("<div class=\"registered\"><?php echo $this->__('Thank you for registration. Your account information will be sent to your email address.');?></div>");
}		 	  

function save_additional(type){

	var firstname= jQuery("#firstname_popup").val();
	var lastname=jQuery("#lastname_popup").val();		 
	var sex=jQuery('input[name=sex_p]:checked', '.sex-field').val();
	var email_str=jQ(type+" #email_address").val();  
	jQ.get('/facebook/facebook/saveadditional',  { email:email_str, sex: sex,fname:firstname,lname:lastname},function(data){              
	if (data=='"success"'){
			popup_close();
			window.location="/customer/account/login/";        			 
      }else{
      	popup_close();        
      	window.location="/customer/account/login/";        	                	
     	}	
	 }); 	 			
	}

function post_request(type,obj) {	  
	  var f =jQuery(obj).closest("form").attr("id");		  
	  var validation=0;
		if (f=='form-validate-to') {
			jQuery("#advice-validate-email-newsletter").remove();
			validation=dataFormto.validator.validate(); 
		}
		if (f=='form-validate-back') {
			jQuery("#advice-validate-email-newsletter").remove();
			validation=dataFormback.validator.validate(); 
		}
		if (f=='form-validate-join') {
			jQuery("#advice-validate-email-newsletter").remove();
			validation=dataFormjoin.validator.validate(); 
		}
	    if (validation){
	        	jQuery(type+" #email_address").css("background-color","#bfffbf");
	       	 	jQuery(type+" #password2").css("background-color","#bfffbf");
			 	jQuery(type+" #password").css("background-color","#bfffbf");    
	            var email_str=jQ(type+" #email_address").val();    
	            var password=jQ(type+" .real-password").val();
	            jQuery(obj).hide(); 
	            jQuery(obj).parent().children(".popup-loader").show(); 
	            jQ.get('/facebook/facebook/login',  { email:email_str, password: password},function(data){              
	            	if (data=='success_0'){
	            		update_account_links();
	            		popup_close();
	            		jQuery(obj).parent().children(".popup-loader").hide();
	            		jQuery(obj).show();
	            		window.location="/customer/account/login/";
	                    }else if (data=='success_1') {
	                    	update_account_links(); 
		                    second_step(type);
		                    jQuery(obj).parent().children(".popup-loader").hide();
		                    jQuery(obj).show();
	            		}else {
		            		if (type=='.express-emails.welcome-back') {
			            		jQuery(type+' .agreement-txt').hide();
		            		}
		            		jQuery("#advice-validate-email-newsletter").remove();
	    					var error_text='<div style="" id="advice-validate-email-newsletter" class="validation-advice">'+data+'</div>';  
	    					if (f=='form-validate-to' || f=='form-validate-join') { 
	    						error_text=error_text.replace("Invalid email or password","This email is already in use");
	    					}					
	    					jQ(type+' .singup-left').append(error_text);  
	    					jQuery(obj).parent().children(".popup-loader").hide();  
	    					jQuery(obj).show();					 
	                    }                
	            },'json'); 
	                   
	      }
}

function forgot_pass(email3){	
	//if (email.length==0){
		email=jQ('.express-emails.welcome-back #email_address').val();
		email2=jQ('.express-emails.welcome-to #email_address').val();
	//} 	
		if (email.length==0 && email2.length!=0){
			email=email2;
		}
		 
		if (email3.length!=0){
			email=email3;
		}
	if (email.length==0){
		jQuery("#advice-validate-email-newsletter").remove();
		var error_text='<div style="" id="advice-validate-email-newsletter" class="validation-advice"><?php echo $this->__("Please fill email field"); ?></div>';
		jQ('.express-emails.welcome-back .singup-left .email-field').append(error_text); 
		jQ('.express-emails.welcome-to .singup-left .email-field').append(error_text);  	
	}
	
	
	if (email.length!=0){
		  		 
		jQ.get('/facebook/facebook/forgotpass',  { email:email,},function(data){
			if (data=='"success_1"') {
			      jQuery("#advice-validate-email-newsletter").remove();
			      var error_text='<div style="" id="advice-validate-email-newsletter" class="validation-advice"><?php echo $this->__("You will receive an email with a link to reset your password."); ?></div>';  
			      jQ('.express-emails.welcome-to .singup-left').append(error_text); 
			      jQ('.express-emails.welcome-to .singup-left #advice-validate-email-newsletter').css("width","301px");	
				  jQ('.express-emails.welcome-back .agreement-txt').html("<?php echo $this->__('You will receive an email with a link to reset your password.');?>");
				} else {
					data2=" <br/>"+data.replace('"','').replace('"','');
				   jQ('.express-emails.welcome-back .agreement-txt').append(data2);	
					jQuery("#advice-validate-email-newsletter").remove();
				    var error_text='<div style="" id="advice-validate-email-newsletter" class="validation-advice">'+data.replace('"','')+'</div>'; 
				    jQ('.express-emails.welcome-to .singup-left').append(error_text); 				   
			}
		 });
	}  	
	//you will receive an email with a link to reset your password.
}


jQuery(document).ready(function() { 
	jQuery(".express-emails :input").each(function() {
		jQuery(this).focusout(function() {
			var f =jQuery(this).closest("form").attr("id");
			validation=0;						
			if (f=='form-validate-to') {
				validation=dataFormto.validator.validate(); 
				//jQuery('#advice-validate-email-newsletter').remove();
			}
			if (f=='form-validate-back') {
				validation=dataFormback.validator.validate(); 
				//jQuery('#advice-validate-email-newsletter').remove();
			}
			if (f=='form-validate-join') {
				validation=dataFormjoin.validator.validate();
				//jQuery('#advice-validate-email-newsletter').remove();
			}
			if (validation==0){
				jQuery('#advice-validate-email-newsletter').remove();
			}
		 });		 		 		 
		});	 
	
  	}); 
	//]]>  	 
</script>
<!-- facebook  -->
<div class="emails-overlay" style="display: none;"></div>
<!-- homepage -->
<?php
$url = Mage::getBaseUrl ( Mage_Core_Model_Store::URL_TYPE_WEB );
$popup_window_enabled=Mage::getStoreConfig('facebook/settings/enabled',Mage::app()->getStore());
 
if (Mage::getSingleton ( 'cms/page' )->getIdentifier () == 'home' && Mage::app ()->getFrontController ()->getRequest ()->getRouteName () == 'cms' && $popup_window_enabled) {
	?>


<div class="express-emails <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?> welcome-to" style="display: none;">
	<div class="express-mails-title <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div>
	<a href="javascript:void(0);" onclick="popup_close();"><div class="express-mails-close <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div></a>
	<div class="singup-info">
		<div class="singup-text"><?php echo $this->__("Do you have your ExpressAccount yet?");?></div>
		<div class="signup-list">
			<ul>
				<li><?php echo $this->__("It's free and quick");?></li>
				<li><?php echo $this->__("Access hidden discounts");?></li>
				<li><?php echo $this->__("Enjoy ExpressCheckout");?></li>
				<li><?php echo $this->__("Get $10 off just for signing up");?></li>
			</ul>
		</div>

	</div>
	<div class="sign-up">
		<form id="form-validate-to" method="post" action="">
			<div class="singup-left">
				<div class="email-field reg-field">
					<div class="email-label reg-label"><?php echo $this->__("Email Address:");?></div>
					<input type="text" class="input-text validate-email required-entry dataFormto" title="Email Address" value="" id="email_address" name="email"  />
				</div>
				<div class="pass-field reg-field">
					<div class="pass-f1">
						<div class="pass-label reg-label"><?php echo $this->__("Password:");?></div>
						<input type="password"
							class="input-text required-entry validate-password real-password"
							title="Password" id="password" name="password" value="" />
					</div>
					<div class="pass-f2">
						<div class="pass-label2 reg-label"><?php echo $this->__("Confirm Password:");?></div>
						<input type="password"
							class="input-text required-entry validate-cpassword real-password2"
							title="Password" id="password2" name="password2" value="" />
					</div>
				</div>
			</div>
			<div class="singup-right">
				<div class="singup-button">
					<button   title="Join" class="button"  onclick="post_request('.express-emails.welcome-to',this);"   type="button"><div><span><?php echo $this->__('Join Us');?></span></div></button>
					<div class="popup-loader" style="display:none;"></div> 
				</div>
				<div class="agreement-txt"><?php echo $this->__('By clicking "Join" you accept our');?><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>facebook-faqs.html"><?php echo $this->__('Terms of Use');?></a><?php echo $this->__(' and');?>					 
						<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>privacy.html"><?php echo $this->__("Privacy Policy");?></a>.
				</div>
			</div>

		</form>
	</div>
	<div class="fb-container">
		<div class="fb-login">
			<a href="#" onclick="return fblogin();" class="fb_button_ps"><div
					class="fb-logo"></div></a>
		</div>
		<div class="fb-text"><?php echo $this->__('ExpressDecor.com will never post without your permission.');?></div>
	</div>
	<div class="footer-cont">
		<div class="member-block">
			<span class="question-part"><?php echo $this->__('Already member?')?></span>
			<span onclick="sign_in();" class="action-part"><?php echo $this->__('Sign in!')?></span>
		</div>
		<div class="footer-text">
		<?php echo $this->__("It's fast and easy. Get access to ExpressAccount Only discounts!");?>
	</div>

	</div>
</div>
<script type="text/javascript">
//<![CDATA[
  var dataFormto = new VarienForm('form-validate-to', false);   	
    jQ.get('/facebook/facebook/islogged',  {},function(data){      
        if (data==0) {
       	jQ('.emails-overlay').show();
        jQ(".express-emails.welcome-to").show();       
        }
    }); 
//]]>  
</script>
<?php } ?>
<!--  welcome back -->
<div class="express-emails welcome-back <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>" style="display: none;">
	<div class="express-mails-title <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div>
	<a href="javascript:void(0);" onclick="popup_close();"><div
			class="express-mails-close <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div></a>
	<div class="singup-info">
		<div class="singup-text"><?php echo $this->__("It's fast and easy. Get access to ExpressAccount Only discounts!");?></div>
	</div>
	<div class="sign-up">
		<form id="form-validate-back" method="post" action="">
			<div class="singup-left">
				<div class="email-field reg-field">
					<div class="email-label reg-label"><?php echo $this->__("Email Address:");?></div>
					<input type="text" class="input-text validate-email required-entry dataFormback"
						title="Email Address" value="" id="email_address" name="email" value="" />
				</div>
				<div class="pass-field reg-field">
					<div class="pass-f1">
						<div class="pass-label reg-label"><?php echo $this->__("Password:");?></div>
						<input type="password"
							class="input-text required-entry validate-password real-password"
							title="Password" id="password" name="password" value="" />
					</div>
				</div>
			</div>
			<div class="singup-right">
				<div class="agreement-txt">					   
					  <?php echo $this->__('<a onclick=\"forgot_pass(\'\');\" href=\"#\">Forgot your password?</a>');?>
				</div>			
				<div class="singup-button">
					<button   title="Sign In" class="button"  onclick="post_request('.express-emails.welcome-back',this);" type="button"><div><span><?php echo $this->__('Sign In');?></span></div></button>
					<div class="popup-loader" style="display:none;"></div>
				</div>
			</div>

		</form>
	</div>

	<div class="fb-container">
		<div class="fb-login">
			<a href="#" onclick="return fblogin();" class="fb_button_ps"><div
					class="fb-logo"></div></a>
		</div>
		<div class="fb-text"><?php echo $this->__('ExpressDecor.com will never post without your permission.');?></div>
	</div>
	<div class="footer-cont">
		<div class="member-block">
			<span class="question-part"><?php echo $this->__('Not a  member yet?')?></span>
			<span onclick="join_us();" class="action-part"><?php echo $this->__('Join Now!')?></span>
		</div>
		<div class="footer-text">
		<?php echo $this->__("Make sure that you can see all of our great savings, sales and discounts!");?>
	</div>

	</div>
</div>
<script type="text/javascript">
//<![CDATA[
  var dataFormback = new VarienForm('form-validate-back', false);
//]]>  	 
</script>
<!-- join us  -->
<div class="express-emails join-us <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>" style="display: none;">
	<div class="express-mails-title <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div>
	<a href="javascript:void(0);" onclick="popup_close();"><div
			class="express-mails-close <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>"></div></a>
	<div class="singup-info">
		<div class="singup-text"><?php echo $this->__("It's fast and easy. Get access to ExpressAccount Only discounts!");?></div>
	</div>
	<div class="sign-up">
		<form id="form-validate-join" method="post" action="">
			<div class="singup-left">
				<div class="email-field reg-field">
					<div class="email-label reg-label"><?php echo $this->__("Email Address:");?></div>
					<input type="text" class="input-text validate-email required-entry dataFormjoin"
						title="Email Address" value="" id="email_address" name="email" value="" />
				</div>
				<div class="pass-field reg-field">
					<div class="pass-f1">
						<div class="pass-label reg-label"><?php echo $this->__("Password:");?></div>
						<input type="password"
							class="input-text required-entry validate-password real-password"
							title="Password" id="password" name="password" value="" />
					</div>
					<div class="pass-f2">
						<div class="pass-label2 reg-label"><?php echo $this->__("Confirm Password:");?></div>
						<input type="password"
							class="input-text required-entry validate-cpassword real-password2"
							title="Password" id="password2" name="password2" value="" />
					</div>
				</div>
			</div>
			<div class="singup-right">
				<div class="agreement-txt">
					<?php echo $this->__('By clicking "Join" you accept our');?><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>facebook-faqs.html"><?php echo $this->__('Terms of Use');?></a><?php echo $this->__(' and');?>					 
						<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>privacy.html"><?php echo $this->__("Privacy Policy");?></a>.
				</div>			
				<div class="singup-button">
					<button   title="Join Us" class="button" onclick="post_request('.express-emails.join-us',this);" type="button"><div><span><?php echo $this->__('Join Us');?></span></div></button>
					<div class="popup-loader" style="display:none;"></div>
				</div>
			</div>

		</form>
		<div class="additional_info"  style="display:none;" >
				<div class="firstname-field reg-field">
					<div class="firstname-label reg-label"><?php echo $this->__("First Name:");?></div>
					<input type="text" class="input-text firstname"
						title="First Name:" value="" id="firstname_popup" name="firstname_p" value="" />
				</div>
				<div class="lastname-field reg-field">
					<div class="email-label reg-label"><?php echo $this->__("Last Name:");?></div>
					<input type="text" class="input-text lastname"
						title="Last Name" value="" id="lastname_popup" name="lastname_p" value="" />
				</div>
				<div class="sex-field reg-field">
					<div class="email-label reg-label"><?php echo $this->__("Gender:");?></div>
					<input type="radio" class="input-text sex" title="Sex" value="1" id="sex_popup" name="sex_p"   /><?php echo $this->__("Male");?> 
					<input type="radio" class="input-text sex" title="Sex" value="2" id="sex_popup" name="sex_p"  /><?php echo $this->__("Female");?> 	
				</div>											
				<div class="save-btn <?php echo $this->htmlEscape(Mage::app()->getStore()->getCode()); ?>">
				<button   title="Save" class="button" onclick="save_additional('.express-emails.join-us');" type="button"><div><span><?php echo $this->__('Continue');?></span></div></button>
				<div class="skip" onclick="popup_close(); window.location='/customer/account/login/';" ><?php echo $this->__('Skip');?></div>
				</div>
				
		
		</div>
	</div>

	<div class="fb-container">
		<div class="fb-login">
			<a href="#" onclick="return fblogin();" class="fb_button_ps"><div class="fb-logo"></div></a>
		</div>
		<div class="fb-text"><?php echo $this->__('ExpressDecor.com will never post without your permission.');?></div>
	</div>
	<div class="footer-cont">
		<div class="member-block">
			<span class="question-part"><?php echo $this->__('Already member?')?></span>
			<span onclick="sign_in();" class="action-part"><?php echo $this->__('Sign in!'); ?></span>			
		</div>
		<div class="footer-text">
		<?php echo $this->__("Make sure that you can see all of our great savings, sales and discounts!");?>
	</div>

	</div>
</div>
<script type="text/javascript">
//<![CDATA[
  var dataFormjoin = new VarienForm('form-validate-join', false);
//]]>  	 
</script>
