<div  class="tabout-left-button" ></div>
<div class="tabout-overlay" style="display:none;"></div>

<div class="tabout_window">
    <div class="tabout_title"><?php echo $this->__('Customer Service'); ?></div>
<div class="tabout_hide" onclick="hide_tabout();"></div>
	<div class="online-content">
	<div class="contact-block call">
		<div class="call-icon"></div>
		<div class="call-us">Call Us</div>
		<div class="inside-text"> Monday - Friday<br>
			<span class="time-working-2">from 9AM to 6PM EST</span>
		</div>
		<div class="phone-icon"></div>
	</div>
	<div class="contact-block chat">
		<div class="chat-icon"></div>
		<div class="live-us">Live Chat with Us</div>
		<div class="inside-text"> Monday - Friday<br>
			<span class="time-working">from 9AM to 6PM EST</span>
		</div>
		<a onclick="lpButtonCTTUrl = 'https://server.iad.liveperson.net/hc/33660894/?cmd=file&amp;file=visitorWantsToChat&amp;site=33660894&amp;imageUrl=https://www.expressdecor.com/templates/ed_new/img/liveperson&amp;referrer='+escape(document.location); lpButtonCTTUrl = (typeof(lpAppendVisitorCookies) != 'undefined' ? lpAppendVisitorCookies(lpButtonCTTUrl) : lpButtonCTTUrl); lpButtonCTTUrl = ((typeof(lpMTag)!='undefined' &amp;&amp; typeof(lpMTag.addFirstPartyCookies)!='undefined')?lpMTag.addFirstPartyCookies(lpButtonCTTUrl):lpButtonCTTUrl);window.open(lpButtonCTTUrl,'chat33660894','width=475,height=400,resizable=yes');return false;" href="https://server.iad.liveperson.net/hc/33660894/?cmd=file&amp;file=visitorWantsToChat&amp;site=33660894&amp;byhref=1&amp;imageUrl=https://www.expressdecor.com/templates/ed_new/img/liveperson">
			<div class="chat-button"></div>
		</a>
	</div>
	 
	</div>       
	<div class="offline-content" >    
		<div class="contact-block last email">
			<div class="email-icon"></div>
			<div class="email-us">Email Us</div>
			<div class="inside-text">Anytime</div>
			<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>contacts"><div class="email-button"></div></a>
		</div>
	</div> 	 
    <div class="express-text">Hours of Operation:</div>
    <div class="express-text time-text"> Today    to    EST </div>    
</div>

<script type="text/javascript">
jQuery(".tabout-left-button").click(function() {
	  jQuery('.tabout_window').show();
	  jQuery('.tabout-overlay').show();
	});
	
function hide_tabout() {	 
	  jQuery('.tabout_window').hide();
	  jQuery('.tabout-overlay').hide();
}

jQuery.get('/set_session.php',  {customer_servive_is_online: 1},function(data){
    var result=JSON.parse( data );	
    if (result.customer_service_online>0) {
    	jQuery('.online-content').show();
    	jQuery(".offline-content").hide();       
    } else {
    	jQuery('.online-content').hide();
    	jQuery(".offline-content").show(); 
    }
    jQuery('.time-text').html('Today '+result.time_from+' to '+result.time_to+' EST');    
    jQuery('.time-working').html('from '+result.time_from+' to '+result.time_to+' EST');
    jQuery('.time-working-2').html('from '+result.time_from+' to '+result.time_to+' EST');
});  
</script>