
<?php 
$hours=array();
$hours=Mage::getStoreConfig('expressdecor/customer_service/service_hours',Mage::app()->getStore());
$hours=json_decode($hours);
$day=date('D', Mage::getModel('core/date')->timestamp(time()));
$last_day=date('D',strtotime('-1 day',Mage::getModel('core/date')->timestamp(time())));

if (strpos($hours->customer_service_time->$last_day->end,'+')>0) {

	$end_time_config_last=$hours->customer_service_time->$last_day->end;
	$end_time_config_last=str_replace('+','',$end_time_config_last);
	
	$h_l=substr($end_time_config_last,0,strpos($end_time_config_last,':'));
	$m_l=substr($end_time_config_last,strpos($end_time_config_last,':')+1,strlen($end_time_config_last)-strpos($end_time_config_last,':')-1);
	
	if (strtotime(date("M-d-Y H:i:s", Mage::getModel('core/date')->timestamp(time())))<mktime($h_l,$m_l,date("s", Mage::getModel('core/date')->timestamp(time())),date("m", Mage::getModel('core/date')->timestamp(time())),date("d", Mage::getModel('core/date')->timestamp(time())),date("Y", Mage::getModel('core/date')->timestamp(time())))) {
		$day=$last_day;
	}
}



$is_open=Mage::getModel('core/session')->getNeedHelp();
 
$end_time_config=$hours->customer_service_time->$day->end;
$start_date=strtotime($hours->customer_service_time->$day->start);

if(strpos($end_time_config,"+")>0)
{
	
	$end_time_config=str_replace('+','',$end_time_config);
	$h=substr($end_time_config,0,strpos($end_time_config,':'));
	$m=substr($end_time_config,strpos($end_time_config,':')+1,strlen($end_time_config)-strpos($end_time_config,':')-1);
	$end_time=mktime($h,$m,date("s", Mage::getModel('core/date')->timestamp(time())),date("m", Mage::getModel('core/date')->timestamp(time())),date("d", Mage::getModel('core/date')->timestamp(time()))+1,date("Y", Mage::getModel('core/date')->timestamp(time())));
	$start_date='0:00';
	
} else {
	$h=substr($end_time_config,0,strpos($end_time_config,':'));
	$m=substr($end_time_config,strpos($end_time_config,':')+1,strlen($end_time_config)-strpos($end_time_config,':')-1);
	$end_time=mktime($h,$m,date("s", Mage::getModel('core/date')->timestamp(time())),date("m", Mage::getModel('core/date')->timestamp(time())),date("d", Mage::getModel('core/date')->timestamp(time())),date("Y", Mage::getModel('core/date')->timestamp(time())));
	
}
if (!isset($is_open)) {
	if ( ($start_date < strtotime(date('H:i', Mage::getModel('core/date')->timestamp(time()))) ) && ( strtotime(date("M-d-Y H:i:s", Mage::getModel('core/date')->timestamp(time()))) < $end_time )  ) {
		$is_open=1;
		Mage::getModel('core/session')->setNeedHelp(1);
	} else {
		$is_open=0;
		Mage::getModel('core/session')->setNeedHelp(0);
	}
}



?>
<div  id="tabout-left-<?php if ( ($start_date < strtotime(date('H:i', Mage::getModel('core/date')->timestamp(time()))) ) && ( strtotime(date("M-d-Y H:i:s", Mage::getModel('core/date')->timestamp(time()))) < $end_time) ) {   ?>aviable<?php } else {   ?>off<?php } ?>" >          
    <div id="handle">   
    </div>    
    <div onclick='simulate(document.getElementById("handle"), "click");' id="express_hide"></div>
<div class="express-title">Customer Service</div>
<?php if ( ($start_date < strtotime(date('H:i', Mage::getModel('core/date')->timestamp(time()))) ) && ( strtotime(date("M-d-Y H:i:s", Mage::getModel('core/date')->timestamp(time()))) < $end_time) ) {   ?>
    <a onclick="lpButtonCTTUrl = 'https://server.iad.liveperson.net/hc/33660894/?cmd=file&amp;file=visitorWantsToChat&amp;site=33660894&amp;imageUrl=https://www.expressdecor.com/templates/ed_new/img/liveperson&amp;referrer='+escape(document.location); lpButtonCTTUrl = (typeof(lpAppendVisitorCookies) != 'undefined' ? lpAppendVisitorCookies(lpButtonCTTUrl) : lpButtonCTTUrl); lpButtonCTTUrl = ((typeof(lpMTag)!='undefined' &amp;&amp; typeof(lpMTag.addFirstPartyCookies)!='undefined')?lpMTag.addFirstPartyCookies(lpButtonCTTUrl):lpButtonCTTUrl);window.open(lpButtonCTTUrl,'chat33660894','width=475,height=400,resizable=yes');return false;" href="https://server.iad.liveperson.net/hc/33660894/?cmd=file&amp;file=visitorWantsToChat&amp;site=33660894&amp;byhref=1&amp;imageUrl=https://www.expressdecor.com/templates/ed_new/img/liveperson">
      <div class="livechat-img-custom" ></div>
                 </a> 
           <div class="livechat-img-right-custom" ></div>
    <?php } else {   ?>
    <div class="express-offline">Currently offline</div>
     <div class="express-email"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>contacts" >
    Send us an Email
      </a> </div>
    <?php } ?>
	     

           <div class="express-text">Hours of Operation:</div>
           <div class="express-text"> Today <? echo date('g A',strtotime($hours->customer_service_time->$day->start))?>  to  <?=date('g A',$end_time)?> EST </div>    
</div>

<script type="text/javascript">Event.observe('handle', 'click',Element.toggleClassName.curry("tabout-left-<?php if ( ($start_date < strtotime(date('H:i', Mage::getModel('core/date')->timestamp(time()))) ) && (  strtotime(date("M-d-Y H:i:s", Mage::getModel('core/date')->timestamp(time()))) < $end_time) ) {   ?>aviable<?php } else {   ?>off<?php } ?>", 'open'));</script>

<?php 
if ($is_open==1) {

	?>
 
	<script type="text/javascript">
	Event.observe('handle', 'click',function(event) {
		new Ajax.Request('/set_session.php',
		{
			method:'get',
			parameters: {customer_show: 0}
		});

	});
</script>

<?php }  ?>