<?php
$taskLists = $this->getTaskLists();
$currentUser = $this->getCurrentUser();
Mage::log('Priorityfilter: '.$this->getPriorityFilter());

$noTasks = true;
?>
<div id="user_task_list">
    <div id="user_task_list_content">
        <h3><?php echo $this->__('My Task List'); ?></h3><a href="#" id="minimise-tasks-list" class="maximize"><?php echo $this->__('maximize'); ?></a>
        <div class="clear"></div>
            <div style="padding:0 0 10px; text-align: right;">
                <?php echo Mage::helper('nicommerce_taskmanager')->__('Filter tasks by priority:'); ?>
                <select id="prioritySelectah">
                    <option value="any"><?php echo Mage::helper('nicommerce_taskmanager')->__('any');?></option>
                    <?php
                    for ( $i=1; $i<=5; $i++ )
                    {
                        echo '<option value="'.$i.'"';
                        if ( $i == $this->getPriorityFilter() ) {
                            echo ' selected ';
                        }
                        echo '>'.Mage::helper('nicommerce_taskmanager')->__($i).'</option>';
                    } ?>
                </select>
            </div>
        <?php if(!$taskLists->getSize()): ?>
        <?php echo $this->__('There are no tasks'); ?>
        <?php else: ?>
        <dl>
            <?php foreach($taskLists as $taskList): ?>
            <?php $userTasks = $taskList->getTasksByUser( $currentUser->getId(), $this->getPriorityFilter() ); ?>
            <?php if(!$userTasks->getSize()) continue; ?>
            <dt><?php echo $taskList->getName(); ?> <a href="#" id="toggleTL<?php echo $taskList->getId(); ?>" onclick="collapseExpand('<?php echo $taskList->getId(); ?>');return false;">(collapse)</a></dt>
            <dd>
                <ul class="tasklist" id="taskList-<?php echo $taskList->getId(); ?>">
                    <?php foreach($userTasks as $userTask): ?>
                    <?php $noTasks = false; ?>
                    <?php $class = ($userTask->getCompletedOn())? ' class="task-completed"': ''; ?>
                    <?php $checked = ($userTask->getCompletedOn())? ' checked="checked"': ''; ?>
                    <li<?php echo $class; ?>>
                        <input type="checkbox" name="mark_as_complete" value="<?php echo $userTask->getId(); ?>"<?php echo $checked; ?> />
                        <span class="task-content"><?php echo $userTask->getContent(); ?></span>
                            <?php $comments = $userTask->getComments(); ?>
                            <?php if( count( $comments ) >0 ): ?>
                            <a href="#" class="showcomments"><?php echo $this->__('Show comments'); ?></a>
                            <div style="display:none;" class="comments">
                                <table style="border:0;" cell-spacing="0" cell-padding="0" border="0">
                                <?php foreach ($comments as $comment): ?>
                                    <tr>
                                        <td style="border:0;" width="20%"><em><?php echo $comment->getUser()->getUsername();?></em></td>
                                        <td style="border:0;" width="80%"><?php echo $comment->getContent();?></td>
                                    </tr>
                                <?php endforeach;?>
                                </table>
                            </div>
                            <?php endif; ?>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php if($noTasks): ?>
        <?php echo $this->__('There are no tasks'); ?>
        <?php endif; ?>
        <?php endif; ?>
    </div>
</div>